### ISSUE TITLE
Music doesn't always play at start

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg-ov#1]
Sometimes, I need to restart the page multiple times to get the music to start.

**Comment by ghost** [comment]
Looking inside the console, I sometimes see `NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.`. I think this is down to the fact that the files are in the `.wav` format.

**Comment by sabianroberts** [comment]
The JS works with WAVs just fine

**Comment by ghost** [comment]
Ah, I've located the issue, some are .wav and some are .mp3. In my array I gave them all a .mp3 extention. Gonna convert them to mp3.

**Comment by sabianroberts** [comment]
The issue still persists for me

**Comment by ghost** [comment]
Did you try hard resetting the page using SHIFT+F5 or CTRL+F5?

**Comment by sabianroberts** [comment]
That seems to work, but still only sometimes.

I think the issue persists because of this: [index.html@L5](https://github.com/OldDigibox/sky-web-epg/blob/master/index.html#L5)
