### ISSUE TITLE
Polish up the CSS for telephone number listings

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg-ov#19]
How it should look:
![Telephone Numbers (4)](https://user-images.githubusercontent.com/31491602/85209552-df0a0780-b330-11ea-9758-031e0b5be9e4.jpg)
How it looks:
![image](https://user-images.githubusercontent.com/31491602/85209557-e5987f00-b330-11ea-86dc-096adb75fef6.png)

**Comment by sabianroberts** [comment]
We've kinda done this, it just needs polishing up.

**Comment by cobaltgit** [comment]
All we need to do now is polish it up so it actually looks like that from the old EPGs
