### ISSUE TITLE
Single music track repeats indefinitely when it's supposed to be a repeated shuffled playlist

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg-ov#2]

**Comment by ghost** [comment]
I reckon the problem here is that you've removed the `loop` attribute from the `audio` tag and replaced it with `shuffle`. Before this change, the EPG music seemed to shuffle just fine.

**Comment by ghost** [comment]
Nevermind. I just reversed the changed on my local clone and the problem persists. I think we might need to review the .js file controlling the EPG music randomiser and make some changes to it.
