### ISSUE TITLE
EPG Music playlist doesn't seem random enough

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg-ov#3]
Every time I refresh the page to change track, I always seem to get the same tracks, so the `epgmusic.js` pattern needs to be made more random because there are 15 tracks and it's only choosing about 4 or 5.

**Comment by ghost** [comment]
I copied the code from a StackOverflow page, since I don't have the best knowldege of JS.
If you want to know where I got it from, [see it here](https://stackoverflow.com/questions/37635281/playing-random-sounds-continuously-on-the-page).

**Comment by sabianroberts** [comment]
I don't know much about JS either lol... I'm strongest at CSS and HTML. I'll have a look at the code later

**Comment by sabianroberts** [comment]
This could be because there isn't enough tracks in some of the folders
