### ISSUE TITLE
Background music no longer plays after recent commits

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg-ov#4]

**Comment by ghost** [comment]
Hm, strange, it plays for me, but with the same not playing sometimes bug. Have you checked the site settings? Sometimes it may block autoplaying audio/video

**Comment by sabianroberts** [comment]
The site settings are fine. The weird thing is that the music plays on Internet Explorer but not Google Chrome which is my primary browser.

**Comment by sabianroberts** [comment]
Turns out that this isn't the issue at all. This was #1 back at it again.
