### ISSUE TITLE
EPG Music JS working when HTML refuses to play music

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg-ov#7]
If you go into the Inspect Element console on Chrome, the _epgsongs.js_ script is embedded into the HTML, which somehow brings up a syntax error and refuses to play music, which is wrong.
![unknown](https://user-images.githubusercontent.com/65132371/81612783-4bf6bd00-93d5-11ea-8191-b4444bf47a8f.png)

**Comment by sabianroberts** [comment]
Hi @PartyEscortBot,

I am aware of this issue and I have pushed my latest attempt to fix it at commit 75631405fb0c28cd7c4f64cab5afbfaacac3592e.

Thanks for posting this issue

-S
